baseurl = "https://cuttytimbers.com"
languageCode = "en-us"
title = "CuttyTimbersMilling"
#theme = "hugo-creative-theme"
googleAnalytics = ""

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.extensions]
#       definitionList = true
#       footnote = true
#       linkify = true
#       strikethrough = true
#       table = true
#       taskList = true
#       typographer = true
#     [markup.goldmark.parser]
#       attribute = true
#       autoHeadingID = true
#       autoHeadingIDType = "github"
#     [markup.goldmark.renderer]
#       hardWraps = false
#       unsafe = false
#       xHTML = false


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "CuttyTimbers.com"
	description = "Cutty Timbers Milling"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Cutty Timbers Milling"

		[params.navigation.links]
			about     = "About"
			services  = "Values"
			portfolio = "Projects & Services"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = ""
		subtitle   = ""
		#buttonText = "CuttyTimbersMilling"


	# About section
	[params.about]
		headline    = "About Us"
		header = "About Us"
		description = """Cutty Timbers Milling started this way, consists of these people, and does this........ kind of work....... maybe part of the Folk Arts & Ecology Guild members
		\nWe offer milling Services, Products including:\n
#### •Milling Shit\n
#### •Making Badass Shit\n
#### •Being Kind\n
#### •And MORE!\n

\n### CHECK OUT OUR PROJECTS & SERVICES BELOW!"""

	# Service section
	[params.services]
		headline = "Our Values"

		[[params.services.list]]
			icon = "fa-smile"
			title = "Relationship"
			description = "We are kind and shit..."

		[[params.services.list]]
			icon = "fa-medal"
			title = "Quality"
			description = "We do shit good"

        [[params.services.list]]
	    	icon = "fa-tree"
			title = "Sustainable"
            description = "Sustainable harvests, green words for the humboldt hippies"

		[[params.services.list]]
			icon = "fa-globe-americas"
			title = "Local"
			description = "Cooperative economies, fuck green diamond and home depot"

		[[params.services.list]]
	  		icon = "fa-mortar-pestle"
            title = "Medicines"
            description = "Oh yeah, and we're witches."

        [[params.services.list]]
            icon = "fa-hiking"
            title = "Mobile"
            description = "Don't get up, we'll come to you"

		[[params.services.list]]
		    icon = "fa-hand-holding-heart"
		    title = "Cooperation"
		    description = "We use our hands for the love-making"

		[[params.services.list]]
		    icon = "fa-carrot"
			title = "Hustlin'"
			description = "'Will mill for food'"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Check Out our Instagram!"

		[params.aside.button]
			text = """We're on the gram!"""
			link = 'https://instagram.com'

	# Contact section
	[params.contact]
		headline = "We Want to Work with You!"
		description = "Ready to start your next project? Have a question about our services? Feel free to GIVE US A CALL or SEND US AN EMAIL and we will get back to you as soon as possible!"
		phone = "555.555.5555"
		email = "contact@cuttytimbers.com"

	 # Google Maps section
     #   [params.location]
	 #	latitude  = "42.52151"
	 #	longitude = "-77.16221"
	 #	maps_api_key = ""
